### ISSUE TITLE
Financial Chart Gadget not charting chains.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/gadgets#18]
**How to recreate**
1. Create a presentation with the financial chart gadget
2. Add a chain to that gadget, in this case use .IXIC (.DJI, .SPX also work)
3. Save presentation and assign to schedule

**What happens**
The chart gadget does show values on the top right, but does not plot any charts.

**What should happen**
Charts should plat on all instruments, even chains.

**Notes**
Presentation: http://bit.ly/26WK8kp

**Comment by alanclayton** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;4qYm0jhw&#x2F;1591-2-some-chain-data-not-showing-in-charts"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> (2) Some Chain data not showing in charts</a>
