### ISSUE TITLE
Financial Gadgets show no data

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/gadgets#45]
### What is the expected behavior?
Financial Gadgets show financial data.

### What is the actual behavior?
Financial Gadgets are blank.  An error is returned constantly in console.

`Uncaught Error: Error handling VM654 jsapi_compiled_default_module.js:379 
    Query strict JSON response: SyntaxError: Unexpected token , in JSON at position 1042
    at VM654 jsapi_compiled_default_module.js:379
    at e.ZJ (VM654 jsapi_compiled_default_module.js:258)
    at gvjs_ok (VM654 jsapi_compiled_default_module.js:261)
    at gvjs_lk (VM654 jsapi_compiled_default_module.js:261)
    at gvjs_bk.Nna (VM654 jsapi_compiled_default_module.js:260)
    at gvjs_$j (VM654 jsapi_compiled_default_module.js:255)`

### What steps can be taken to replicate the problem?
Add a marketwall built in classic editor to a display schedule.

**Comment by PatrickA-RiseVision** [comment]
Can you please have a look and let us know what the scope is and what kind of effort it would be to resolve so Support can discuss options?  This is potentially impacting some of the highest MRR accounts.

**Comment by ezequielc** [comment]
As per https://rise-vision-inc.slack.com/archives/C0189N0RGM9, this is now resolved. Thanks!
